[package]
name = "scors"
version = "0.1.0"
edition = "2021"

[lib]
name = "scors"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.5", features = ["extension-module"] }
numpy = "0.23.0"

